version: "3.9"
services:
  beesrun:
    image: nginx
    ports:
    - 8000:8000
    - 80:80
    - 443:443
    volumes:
    - /etc/letsencrypt/archive/bees.run/fullchain1.pem:/var/www/letsencrypt/fullchain.pem:ro
    - /etc/letsencrypt/archive/bees.run/privkey1.pem:/var/www/letsencrypt/privkey.pem:ro
    - /etc/nginx/:/etc/nginx:ro