[package]
name = "pastebee"
version = "0.1.0"
edition = "2021"

[dependencies]
const_format = "0.2.30"
rocket = { version = "0.5.0-rc.2", features = ["json", "secrets"] }
rand = "0.8"
sqlx = "0.5"

[dependencies.rocket_db_pools]
version = "0.1.0-rc.2"
features = ["sqlx_sqlite"]